//
//  AppLanguageManager.swift
//  Unizo_iOS
//
//  Runtime language manager for switching app language without .lproj files.
//  Stores the selected language in UserDefaults and provides translated strings.
//

import Foundation
import UIKit

// MARK: - Supported Languages
enum AppLanguage: String, CaseIterable {
    case english  = "English"
    case hindi    = "Hindi"
    case spanish  = "Spanish"
    case french   = "French"
    case german   = "German"
}

// MARK: - Language Manager
final class AppLanguageManager {

    static let shared = AppLanguageManager()

    private let defaults = UserDefaults.standard
    private let key = "app_selected_language"

    private(set) var current: AppLanguage = .english

    private init() {
        if let saved = defaults.string(forKey: key),
           let lang = AppLanguage(rawValue: saved) {
            current = lang
        }
    }

    func setLanguage(_ language: AppLanguage) {
        current = language
        defaults.set(language.rawValue, forKey: key)
        print("\u{1F310} Language changed to: \(language.rawValue)")
    }

    /// Returns the translated string for the given English key.
    func localized(_ english: String) -> String {
        guard current != .english else { return english }
        return translations[current]?[english] ?? english
    }

    // MARK: - Translation Dictionaries
    // Strings not found fall back to English.

    private let translations: [AppLanguage: [String: String]] = [

        // MARK: Hindi
        .hindi: [
            // Tab Bar
            "Home": "होम",
            "Search": "खोजें",
            "Sell": "बेचें",
            "Post": "पोस्ट",
            "Chat": "चैट",
            "Account": "खाता",

            // Settings
            "Settings": "सेटिंग्स",
            "Preferences": "प्राथमिकताएं",
            "Support": "सहायता",
            "Security": "सुरक्षा",
            "Account Actions": "खाता कार्रवाई",
            "Language": "भाषा",
            "Push Notifications": "पुश सूचनाएं",
            "Email Marketing": "ईमेल मार्केटिंग",
            "Contact Us": "संपर्क करें",
            "Rate Our App": "ऐप को रेट करें",
            "Change Password": "पासवर्ड बदलें",
            "Biometric Login": "बायोमेट्रिक लॉगिन",
            "Sign Out": "साइन आउट",
            "Delete Account": "खाता हटाएं",

            // Language Screen
            "Choose the language": "भाषा चुनें",
            "Select your preferred language below. This helps us serve you better.": "नीचे अपनी पसंदीदा भाषा चुनें। यह हमें आपकी बेहतर सेवा करने में मदद करता है।",
            "You Selected": "आपने चुना",
            "All Languages": "सभी भाषाएं",

            // Change Password
            "Enter old password:": "पुराना पासवर्ड दर्ज करें:",
            "Enter new password:": "नया पासवर्ड दर्ज करें:",
            "Old Password": "पुराना पासवर्ड",
            "New Password": "नया पासवर्ड",
            "Forgot Password?": "पासवर्ड भूल गए?",
            "Save": "सहेजें",
            "Password Changed": "पासवर्ड बदला गया",
            "Your password has been updated successfully.": "आपका पासवर्ड सफलतापूर्वक अपडेट किया गया है।",

            // Reset Password
            "Set New Password": "नया पासवर्ड सेट करें",
            "Enter and confirm your new password below.": "नीचे अपना नया पासवर्ड दर्ज करें और पुष्टि करें।",
            "Reset Your Password": "अपना पासवर्ड रीसेट करें",
            "Confirm Password": "पासवर्ड की पुष्टि करें",
            "College Email": "कॉलेज ईमेल",
            "Update Password": "पासवर्ड अपडेट करें",
            "Send Reset Link": "रीसेट लिंक भेजें",
            "Back to Login.": "लॉगिन पर वापस जाएं।",
            "Password Updated": "पासवर्ड अपडेट किया गया",
            "Your password has been changed successfully.": "आपका पासवर्ड सफलतापूर्वक बदल दिया गया है।",
            "Reset Link Sent": "रीसेट लिंक भेजा गया",

            // Contact Us
            "How Can We Reach You?": "हम आपसे कैसे संपर्क करें?",
            "What Can We Help You With?": "हम आपकी किस तरह मदद कर सकते हैं?",
            "Briefly Explain What's Going On": "संक्षेप में बताएं क्या हो रहा है",
            "Email": "ईमेल",
            "Phone": "फ़ोन",
            "Email Address": "ईमेल पता",
            "Phone Number": "फ़ोन नंबर",
            "Subject": "विषय",
            "Message": "संदेश",
            "Submit": "भेजें",
            "Help": "सहायता",
            "Bug Report": "बग रिपोर्ट",
            "Feedback": "प्रतिक्रिया",
            "Account Issue": "खाता समस्या",
            "Write your message here...": "अपना संदेश यहां लिखें...",

            // Common
            "OK": "ठीक है",
            "Cancel": "रद्द करें",
            "Continue": "जारी रखें",
            "Get Help": "सहायता प्राप्त करें",
            "Back": "वापस",
            "Loading...": "लोड हो रहा है...",
            "Error": "त्रुटि",
            "Success": "सफल",
            "Delete": "हटाएं",
            "Done": "हो गया",
            "Edit": "संपादित करें",
            "Discard": "खारिज करें",
            "All": "सभी",

            // Home
            "Trending Categories": "ट्रेंडिंग श्रेणियां",
            "Categories": "श्रेणियां",
            "See All": "सभी देखें",
            "Popular Items": "लोकप्रिय वस्तुएं",
            "Most Popular": "सबसे लोकप्रिय",
            "Negotiable": "सौदेबाज़ी योग्य",
            "Hostel Essentials": "हॉस्टल की ज़रूरतें",
            "Furniture": "फर्नीचर",
            "Fashion": "फैशन",
            "Sports": "खेल",
            "Gadgets": "गैजेट्स",

            // Chat
            "No conversations yet": "अभी कोई बातचीत नहीं",
            "Start chatting with sellers\nby tapping Chat on a product": "किसी उत्पाद पर चैट टैप करके\nविक्रेताओं से चैट शुरू करें",
            "Type a message...": "एक संदेश लिखें...",
            "Start a conversation": "बातचीत शुरू करें",
            "Selling": "बिक्री",
            "Buying": "खरीदारी",
            "Buyer": "खरीदार",
            "Seller": "विक्रेता",
            "Sending photo...": "फ़ोटो भेज रहा है...",
            "Failed to Send": "भेजने में विफल",
            "Could not send the photo. Please try again.": "फ़ोटो भेजी नहीं जा सकी। कृपया पुनः प्रयास करें।",

            // Orders
            "My Orders": "मेरे ऑर्डर",
            "Order Details": "ऑर्डर विवरण",
            "Pending": "लंबित",
            "Confirmed": "पुष्टि की गई",
            "Delivered": "वितरित",
            "Cancelled": "रद्द",
            "Processing": "प्रक्रिया में",
            "No orders yet": "अभी कोई ऑर्डर नहीं",
            "Failed to load orders": "ऑर्डर लोड करने में विफल",
            "Order Timeline": "ऑर्डर टाइमलाइन",
            "Order Items": "ऑर्डर आइटम",
            "Delivery Information": "डिलीवरी जानकारी",
            "Order Summary": "ऑर्डर सारांश",
            "Subtotal": "उप-योग",
            "Negotiation Discount": "सौदेबाज़ी छूट",
            "Total": "कुल",
            "Rate Order": "ऑर्डर रेट करें",
            "Order Confirmed": "ऑर्डर की पुष्टि हुई",
            "Order Placed": "ऑर्डर दिया गया",
            "Order Delivered": "ऑर्डर वितरित",
            "Order Declined": "ऑर्डर अस्वीकृत",
            "Ready for Handoff": "हैंडऑफ़ के लिए तैयार",
            "Ready to Meet": "मिलने के लिए तैयार",
            "Verify Code": "कोड सत्यापित करें",
            "Enter 6-digit code": "6 अंकों का कोड दर्ज करें",
            "Loading order items...": "ऑर्डर आइटम लोड हो रहे हैं...",
            "Colour": "रंग",
            "Size": "आकार",
            "Quantity": "मात्रा",
            "Confirm Order": "ऑर्डर की पुष्टि करें",
            "Place Order": "ऑर्डर दें",
            "Accept Order": "ऑर्डर स्वीकार करें",
            "Reject Order": "ऑर्डर अस्वीकार करें",

            // Listings
            "My Listings": "मेरी लिस्टिंग",
            "No listings yet": "अभी कोई लिस्टिंग नहीं",
            "Search listings...": "लिस्टिंग खोजें...",
            "Available": "उपलब्ध",
            "Sold": "बिका",
            "Start selling by posting\nyour first item": "अपना पहला आइटम पोस्ट करके\nबेचना शुरू करें",
            "No results found": "कोई परिणाम नहीं मिला",
            "Try a different search term": "एक अलग खोज शब्द आज़माएं",
            "Items with this status\nwill appear here": "इस स्थिति वाले आइटम\nयहां दिखाई देंगे",
            "Cannot Edit": "संपादित नहीं कर सकते",
            "Once sold, listing cannot be edited.": "बिकने के बाद, लिस्टिंग संपादित नहीं की जा सकती।",
            "Delete Listing": "लिस्टिंग हटाएं",
            "Edit Listing": "लिस्टिंग संपादित करें",

            // Item Details
            "Description": "विवरण",
            "Features": "विशेषताएं",
            "Condition": "स्थिति",
            "Deal": "सौदा",
            "Item Unavailable": "आइटम उपलब्ध नहीं",
            "No description available.": "कोई विवरण उपलब्ध नहीं।",
            "No features listed.": "कोई विशेषता सूचीबद्ध नहीं।",

            // Post Item
            "Post Item": "आइटम पोस्ट करें",
            "Upload Photos": "फ़ोटो अपलोड करें",
            "Product Details": "उत्पाद विवरण",
            "Product Name": "उत्पाद का नाम",
            "Price (in Rupees)": "कीमत (रुपये में)",
            "Category": "श्रेणी",
            "Upload Product": "उत्पाद अपलोड करें",
            "Non-Negotiable": "सौदेबाज़ी अयोग्य",
            "Authentication Required": "प्रमाणीकरण आवश्यक",
            "Please log in to post items": "आइटम पोस्ट करने के लिए कृपया लॉगिन करें",
            "Missing Information": "जानकारी अधूरी है",
            "Please fill in all required fields": "कृपया सभी आवश्यक फ़ील्ड भरें",
            "Product uploaded successfully!": "उत्पाद सफलतापूर्वक अपलोड किया गया!",
            "Save Changes": "परिवर्तन सहेजें",
            "Update Listing": "लिस्टिंग अपडेट करें",

            // Notifications
            "Notifications": "सूचनाएं",
            "No notifications yet": "अभी कोई सूचना नहीं",
            "Failed to load notifications": "सूचनाएं लोड करने में विफल",

            // Profile
            "Profile": "प्रोफ़ाइल",
            "Personal Information": "व्यक्तिगत जानकारी",
            "Hotspot Information": "हॉटस्पॉट जानकारी",
            "First Name": "पहला नाम",
            "Last Name": "अंतिम नाम",
            "Date of Birth": "जन्म तिथि",
            "Gender": "लिंग",
            "Address": "पता",
            "City": "शहर",
            "State": "राज्य",
            "ZIP Code": "पिन कोड",
            "Male": "पुरुष",
            "Female": "महिला",
            "Neutral": "तटस्थ",
            "Email Notifications": "ईमेल सूचनाएं",
            "SMS Notifications": "एसएमएस सूचनाएं",
            "Edit Profile": "प्रोफाइल संपादित करें",
            "Discard Changes?": "परिवर्तन खारिज करें?",
            "You have unsaved changes. Are you sure you want to go back?": "आपके असहेजे परिवर्तन हैं। क्या आप वापस जाना चाहते हैं?",

            // Wishlist
            "My Wishlist": "मेरी इच्छा सूची",
            "Wishlist": "इच्छा सूची",
            "My Addresses": "मेरे पते",
            "Terms & Conditions": "नियम और शर्तें",
            "Privacy Policy": "गोपनीयता नीति",

            // Address
            "Add New Address": "नया पता जोड़ें",
            "Add Address": "पता जोड़ें",
            "Street": "गली",
            "Country": "देश",

            // Confirm Order
            "Delivery Address": "डिलीवरी पता",
            "Change": "बदलें",
            "Payment Method": "भुगतान विधि",
            "Cash on Delivery": "कैश ऑन डिलीवरी",
            "Special Instructions": "विशेष निर्देश",
            "Review": "समीक्षा",
            "Payment": "भुगतान",

            // Events
            "Events": "कार्यक्रम",
            "Browse Events": "कार्यक्रम देखें",

            // Post Chooser & Post Event
            "What would you like to post?": "आप क्या पोस्ट करना चाहेंगे?",
            "Choose an option below to get started.": "शुरू करने के लिए नीचे एक विकल्प चुनें।",
            "Post an Item": "आइटम पोस्ट करें",
            "Post an Event": "इवेंट पोस्ट करें",
            "List a product for sale on the marketplace.": "मार्केटप्लेस पर बिक्री के लिए उत्पाद सूचीबद्ध करें।",
            "Create a campus event for others to discover.": "दूसरों के लिए कैंपस इवेंट बनाएं।",
            "Post Event": "इवेंट पोस्ट करें",
            "Event Details": "इवेंट विवरण",
            "Event Title": "इवेंट शीर्षक",
            "Venue": "स्थान",
            "Date": "तारीख",
            "Time": "समय",
            "Free Event": "मुफ़्त इवेंट",
            "Tap to add an event image": "इवेंट इमेज जोड़ने के लिए टैप करें",
            "Describe your event...": "अपने इवेंट का वर्णन करें...",
            "Your event has been posted successfully!": "आपका इवेंट सफलतापूर्वक पोस्ट हो गया है!",
            "Your Event has been posted!": "आपका इवेंट पोस्ट हो गया है!",
            "Users can now discover and register for your event.": "उपयोगकर्ता अब आपके इवेंट को खोज और पंजीकरण कर सकते हैं।",
            "View Events": "इवेंट देखें",
            "Please enter a valid price or mark the event as free.": "कृपया एक मान्य कीमत दर्ज करें या इवेंट को मुफ़्त चिह्नित करें।",
            "Please fill in all required fields.": "कृपया सभी आवश्यक फ़ील्ड भरें।",

            // Auth
            "Login": "लॉगिन",
            "Welcome Back": "वापसी पर स्वागत",
            "Sign Up": "साइन अप",
            "Create Account": "खाता बनाएं",
            "Password": "पासवर्ड",
            "Already have an account?": "पहले से खाता है?",
            "Account Created": "खाता बनाया गया",
            "Get Started": "शुरू करें",
            "Welcome": "स्वागत",
            "Order Placed!": "ऑर्डर दिया गया!",
            "Continue Shopping": "खरीदारी जारी रखें",
            "View Order": "ऑर्डर देखें",

            // Rate App
            "Rate Unizo": "Unizo को रेट करें",
            "You'll be redirected to our app page on the App Store where you can leave a rating and review.": "आपको ऐप स्टोर पर हमारे ऐप पेज पर रीडायरेक्ट किया जाएगा जहां आप रेटिंग और समीक्षा दे सकते हैं।",

            // Sign Out / Delete
            "Are you sure you want to sign out?": "क्या आप साइन आउट करना चाहते हैं?",
            "Are you sure you want to delete your account? This action cannot be undone.": "क्या आप अपना खाता हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।",

            // Handoff
            "Show this code to the seller when you meet to confirm delivery.": "डिलीवरी की पुष्टि के लिए जब आप मिलें तो विक्रेता को यह कोड दिखाएं।",
            "Enter the code the buyer shows you to confirm delivery.": "डिलीवरी की पुष्टि के लिए खरीदार द्वारा दिखाया गया कोड दर्ज करें।",
            "Please enter the full 6-digit code.": "कृपया पूरा 6 अंकों का कोड दर्ज करें।",
            "Incorrect code. Please try again.": "गलत कोड। कृपया पुनः प्रयास करें।",
            "Something went wrong. Please try again.": "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",

            // New Localization Keys
            // Settings Alerts
            "Failed to sign out: %@": "%@ साइन आउट करने में विफल:",
            "Are you sure you want to delete your account? This action cannot be undone and all your data will be permanently removed.": "क्या आप वाकई अपना खाता हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती और आपका सारा डेटा स्थायी रूप से हटा दिया जाएगा।",
            "Failed to delete account: %@": "खाता हटाने में विफल: %@",

            // Account
            "Guest": "अतिथि",
            "Not signed in": "साइन इन नहीं है",

            // Edit Address
            "Edit Hotspot": "हॉटस्पॉट संपादित करें",
            "Set as default hotspot": "डिफ़ॉल्ट हॉटस्पॉट सेट करें",

            // Product Posted
            "Your Product has been posted!": "आपका उत्पाद पोस्ट हो गया है!",
            "We'll reach out to the best valued customers.": "हम सबसे अच्छे ग्राहकों तक पहुंचेंगे।",
            "View Listings": "लिस्टिंग देखें",

            // Payments
            "Payments": "भुगतान",
            "Cards": "कार्ड",
            "UPI": "UPI",
            "Add credit or debit cards": "क्रेडिट या डेबिट कार्ड जोड़ें",
            "Google Pay UPI": "Google Pay UPI",
            "PhonePe UPI": "PhonePe UPI",
            "BHIM UPI": "BHIM UPI",
            "Add new UPI ID": "नई UPI ID जोड़ें",
            "Add": "जोड़ें",

            // Seller Dashboard
            "Dashboard": "डैशबोर्ड",
            "Breakdown": "विवरण",
            "Failed to load dashboard data": "डैशबोर्ड डेटा लोड करने में विफल",
            "Retry": "पुनः प्रयास करें",

            // Search
            "Recent Searches": "हाल की खोजें",

            // Terms
            "Terms and Conditions": "नियम और शर्तें",

            // Events
            "Book Now": "अभी बुक करें",

            // Listings
            "No %@ listings": "कोई %@ लिस्टिंग नहीं",
            "%d listings • %d available • %d sold": "%d लिस्टिंग • %d उपलब्ध • %d बिके",
            "Are you sure you want to delete \"%@\"?": "क्या आप \"%@\" को हटाना चाहते हैं?",

            // Enhanced Listing
            "%d views": "%d दृश्य",
            "Qty: %d": "मात्रा: %d",
            "Buyer: %@": "खरीदार: %@",

            // Order Card
            "Order #%@": "ऑर्डर #%@",
            "Placed on %@": "%@ को ऑर्डर किया",
            "Total: ₹%@": "कुल: ₹%@",
            "Total: ₹%d": "कुल: ₹%d",
            "+%d more items →": "+%d और आइटम →",
            "+%d more item →": "+%d और आइटम →",
            "No items": "कोई आइटम नहीं",

            // Reset Password
            "Don't worry! Enter your email address and we'll send\nyou a link to reset your password.": "चिंता न करें! अपना ईमेल दर्ज करें और हम आपको पासवर्ड रीसेट लिंक भेजेंगे।",
            "We've sent a password reset link to %@. Please check your inbox and spam folder.": "हमने %@ पर पासवर्ड रीसेट लिंक भेजा है। कृपया अपना इनबॉक्स और स्पैम फ़ोल्डर जांचें।",
        ],

        // MARK: Spanish
        .spanish: [
            "Home": "Inicio",
            "Search": "Buscar",
            "Sell": "Vender",
            "Post": "Publicar",
            "Chat": "Chat",
            "Account": "Cuenta",

            "Settings": "Ajustes",
            "Preferences": "Preferencias",
            "Support": "Soporte",
            "Security": "Seguridad",
            "Account Actions": "Acciones de Cuenta",
            "Language": "Idioma",
            "Push Notifications": "Notificaciones Push",
            "Email Marketing": "Marketing por Email",
            "Contact Us": "Contáctanos",
            "Rate Our App": "Califica Nuestra App",
            "Change Password": "Cambiar Contraseña",
            "Biometric Login": "Inicio Biométrico",
            "Sign Out": "Cerrar Sesión",
            "Delete Account": "Eliminar Cuenta",

            "Choose the language": "Elige el idioma",
            "Select your preferred language below. This helps us serve you better.": "Selecciona tu idioma preferido abajo. Esto nos ayuda a atenderte mejor.",
            "You Selected": "Seleccionaste",
            "All Languages": "Todos los Idiomas",

            "Enter old password:": "Ingresa la contraseña anterior:",
            "Enter new password:": "Ingresa la nueva contraseña:",
            "Old Password": "Contraseña Anterior",
            "New Password": "Nueva Contraseña",
            "Forgot Password?": "¿Olvidaste tu Contraseña?",
            "Save": "Guardar",
            "Password Changed": "Contraseña Cambiada",
            "Your password has been updated successfully.": "Tu contraseña se ha actualizado correctamente.",

            "Set New Password": "Establecer Nueva Contraseña",
            "Enter and confirm your new password below.": "Ingresa y confirma tu nueva contraseña abajo.",
            "Reset Your Password": "Restablece tu Contraseña",
            "Confirm Password": "Confirmar Contraseña",
            "College Email": "Correo Universitario",
            "Update Password": "Actualizar Contraseña",
            "Send Reset Link": "Enviar Enlace de Restablecimiento",
            "Back to Login.": "Volver al Inicio de Sesión.",
            "Password Updated": "Contraseña Actualizada",
            "Your password has been changed successfully.": "Tu contraseña se ha cambiado correctamente.",
            "Reset Link Sent": "Enlace de Restablecimiento Enviado",

            "How Can We Reach You?": "¿Cómo podemos contactarte?",
            "What Can We Help You With?": "¿En qué podemos ayudarte?",
            "Briefly Explain What's Going On": "Explica brevemente qué sucede",
            "Email": "Correo",
            "Phone": "Teléfono",
            "Email Address": "Dirección de Correo",
            "Phone Number": "Número de Teléfono",
            "Subject": "Asunto",
            "Message": "Mensaje",
            "Submit": "Enviar",
            "Help": "Ayuda",
            "Bug Report": "Reporte de Error",
            "Feedback": "Comentarios",
            "Account Issue": "Problema de Cuenta",
            "Write your message here...": "Escribe tu mensaje aquí...",

            "OK": "OK",
            "Cancel": "Cancelar",
            "Continue": "Continuar",
            "Get Help": "Obtener Ayuda",
            "Back": "Atrás",
            "Loading...": "Cargando...",
            "Error": "Error",
            "Success": "Éxito",
            "Delete": "Eliminar",
            "Done": "Hecho",
            "Edit": "Editar",
            "Discard": "Descartar",
            "All": "Todos",

            "Trending Categories": "Categorías en Tendencia",
            "Categories": "Categorías",
            "See All": "Ver Todo",
            "Popular Items": "Artículos Populares",
            "Most Popular": "Más Popular",
            "Negotiable": "Negociable",
            "Hostel Essentials": "Esenciales del Hostel",
            "Furniture": "Muebles",
            "Fashion": "Moda",
            "Sports": "Deportes",
            "Gadgets": "Gadgets",

            "No conversations yet": "Sin conversaciones aún",
            "Start chatting with sellers\nby tapping Chat on a product": "Comienza a chatear con vendedores\ntocando Chat en un producto",
            "Type a message...": "Escribe un mensaje...",
            "Start a conversation": "Iniciar una conversación",
            "Selling": "Vendiendo",
            "Buying": "Comprando",
            "Buyer": "Comprador",
            "Seller": "Vendedor",
            "Sending photo...": "Enviando foto...",
            "Failed to Send": "Error al Enviar",
            "Could not send the photo. Please try again.": "No se pudo enviar la foto. Inténtalo de nuevo.",

            "My Orders": "Mis Pedidos",
            "Order Details": "Detalles del Pedido",
            "Pending": "Pendiente",
            "Confirmed": "Confirmado",
            "Delivered": "Entregado",
            "Cancelled": "Cancelado",
            "Processing": "Procesando",
            "No orders yet": "Sin pedidos aún",
            "Failed to load orders": "Error al cargar pedidos",
            "Order Timeline": "Línea de Tiempo del Pedido",
            "Order Items": "Artículos del Pedido",
            "Delivery Information": "Información de Entrega",
            "Order Summary": "Resumen del Pedido",
            "Subtotal": "Subtotal",
            "Negotiation Discount": "Descuento por Negociación",
            "Total": "Total",
            "Rate Order": "Calificar Pedido",
            "Order Confirmed": "Pedido Confirmado",
            "Order Placed": "Pedido Realizado",
            "Order Delivered": "Pedido Entregado",
            "Order Declined": "Pedido Rechazado",
            "Ready for Handoff": "Listo para Entrega",
            "Ready to Meet": "Listo para Encontrarse",
            "Verify Code": "Verificar Código",
            "Enter 6-digit code": "Ingresa código de 6 dígitos",
            "Loading order items...": "Cargando artículos del pedido...",
            "Colour": "Color",
            "Size": "Talla",
            "Quantity": "Cantidad",
            "Confirm Order": "Confirmar Pedido",
            "Place Order": "Realizar Pedido",
            "Accept Order": "Aceptar Pedido",
            "Reject Order": "Rechazar Pedido",

            "My Listings": "Mis Publicaciones",
            "No listings yet": "Sin publicaciones aún",
            "Search listings...": "Buscar publicaciones...",
            "Available": "Disponible",
            "Sold": "Vendido",
            "Start selling by posting\nyour first item": "Empieza a vender publicando\ntu primer artículo",
            "No results found": "Sin resultados",
            "Try a different search term": "Prueba un término de búsqueda diferente",
            "Items with this status\nwill appear here": "Los artículos con este estado\naparecerán aquí",
            "Cannot Edit": "No se puede Editar",
            "Once sold, listing cannot be edited.": "Una vez vendido, no se puede editar.",
            "Delete Listing": "Eliminar Publicación",
            "Edit Listing": "Editar Publicación",

            "Description": "Descripción",
            "Features": "Características",
            "Condition": "Condición",
            "Deal": "Trato",
            "Item Unavailable": "Artículo No Disponible",
            "No description available.": "Sin descripción disponible.",
            "No features listed.": "Sin características listadas.",

            "Post Item": "Publicar Artículo",
            "Upload Photos": "Subir Fotos",
            "Product Details": "Detalles del Producto",
            "Product Name": "Nombre del Producto",
            "Price (in Rupees)": "Precio (en Rupias)",
            "Category": "Categoría",
            "Upload Product": "Subir Producto",
            "Non-Negotiable": "No Negociable",
            "Authentication Required": "Autenticación Requerida",
            "Please log in to post items": "Inicia sesión para publicar artículos",
            "Missing Information": "Información Faltante",
            "Please fill in all required fields": "Completa todos los campos requeridos",
            "Product uploaded successfully!": "¡Producto subido correctamente!",
            "Save Changes": "Guardar Cambios",
            "Update Listing": "Actualizar Publicación",

            "Notifications": "Notificaciones",
            "No notifications yet": "Sin notificaciones aún",
            "Failed to load notifications": "Error al cargar notificaciones",

            "Profile": "Perfil",
            "Personal Information": "Información Personal",
            "Hotspot Information": "Información del Punto de Encuentro",
            "First Name": "Nombre",
            "Last Name": "Apellido",
            "Date of Birth": "Fecha de Nacimiento",
            "Gender": "Género",
            "Address": "Dirección",
            "City": "Ciudad",
            "State": "Estado",
            "ZIP Code": "Código Postal",
            "Male": "Masculino",
            "Female": "Femenino",
            "Neutral": "Neutro",
            "Email Notifications": "Notificaciones por Correo",
            "SMS Notifications": "Notificaciones SMS",
            "Edit Profile": "Editar Perfil",
            "Discard Changes?": "¿Descartar Cambios?",
            "You have unsaved changes. Are you sure you want to go back?": "Tienes cambios sin guardar. ¿Estás seguro de que quieres volver?",

            "My Wishlist": "Mi Lista de Deseos",
            "Wishlist": "Lista de Deseos",
            "My Addresses": "Mis Direcciones",
            "Terms & Conditions": "Términos y Condiciones",
            "Privacy Policy": "Política de Privacidad",

            "Add New Address": "Agregar Nueva Dirección",
            "Add Address": "Agregar Dirección",
            "Street": "Calle",
            "Country": "País",

            "Delivery Address": "Dirección de Entrega",
            "Change": "Cambiar",
            "Payment Method": "Método de Pago",
            "Cash on Delivery": "Pago Contra Entrega",
            "Special Instructions": "Instrucciones Especiales",
            "Review": "Revisar",
            "Payment": "Pago",

            "Events": "Eventos",
            "Browse Events": "Explorar Eventos",

            // Post Chooser & Post Event
            "What would you like to post?": "¿Qué te gustaría publicar?",
            "Choose an option below to get started.": "Elige una opción a continuación para comenzar.",
            "Post an Item": "Publicar un Artículo",
            "Post an Event": "Publicar un Evento",
            "List a product for sale on the marketplace.": "Publica un producto a la venta en el mercado.",
            "Create a campus event for others to discover.": "Crea un evento universitario para que otros lo descubran.",
            "Post Event": "Publicar Evento",
            "Event Details": "Detalles del Evento",
            "Event Title": "Título del Evento",
            "Venue": "Lugar",
            "Date": "Fecha",
            "Time": "Hora",
            "Free Event": "Evento Gratuito",
            "Tap to add an event image": "Toca para agregar una imagen del evento",
            "Describe your event...": "Describe tu evento...",
            "Your event has been posted successfully!": "¡Tu evento se ha publicado exitosamente!",
            "Your Event has been posted!": "¡Tu Evento ha sido publicado!",
            "Users can now discover and register for your event.": "Los usuarios ahora pueden descubrir y registrarse en tu evento.",
            "View Events": "Ver Eventos",
            "Please enter a valid price or mark the event as free.": "Ingresa un precio válido o marca el evento como gratuito.",
            "Please fill in all required fields.": "Por favor completa todos los campos requeridos.",

            "Login": "Iniciar Sesión",
            "Welcome Back": "Bienvenido de Nuevo",
            "Sign Up": "Registrarse",
            "Create Account": "Crear Cuenta",
            "Password": "Contraseña",
            "Already have an account?": "¿Ya tienes una cuenta?",
            "Account Created": "Cuenta Creada",
            "Get Started": "Comenzar",
            "Welcome": "Bienvenido",
            "Order Placed!": "¡Pedido Realizado!",
            "Continue Shopping": "Seguir Comprando",
            "View Order": "Ver Pedido",

            "Rate Unizo": "Califica Unizo",
            "You'll be redirected to our app page on the App Store where you can leave a rating and review.": "Serás redirigido a nuestra página en la App Store donde podrás dejar una calificación y reseña.",

            "Are you sure you want to sign out?": "¿Estás seguro de que quieres cerrar sesión?",
            "Are you sure you want to delete your account? This action cannot be undone.": "¿Estás seguro de que quieres eliminar tu cuenta? Esta acción no se puede deshacer.",

            "Show this code to the seller when you meet to confirm delivery.": "Muestra este código al vendedor cuando se encuentren para confirmar la entrega.",
            "Enter the code the buyer shows you to confirm delivery.": "Ingresa el código que el comprador te muestra para confirmar la entrega.",
            "Please enter the full 6-digit code.": "Ingresa el código completo de 6 dígitos.",
            "Incorrect code. Please try again.": "Código incorrecto. Inténtalo de nuevo.",
            "Something went wrong. Please try again.": "Algo salió mal. Inténtalo de nuevo.",

            // New Localization Keys
            "Failed to sign out: %@": "Error al cerrar sesión: %@",
            "Are you sure you want to delete your account? This action cannot be undone and all your data will be permanently removed.": "¿Estás seguro de que quieres eliminar tu cuenta? Esta acción no se puede deshacer y todos tus datos se eliminarán permanentemente.",
            "Failed to delete account: %@": "Error al eliminar la cuenta: %@",
            "Guest": "Invitado",
            "Not signed in": "No has iniciado sesión",
            "Edit Hotspot": "Editar punto de encuentro",
            "Set as default hotspot": "Establecer como punto predeterminado",
            "Your Product has been posted!": "¡Tu producto ha sido publicado!",
            "We'll reach out to the best valued customers.": "Llegaremos a los mejores clientes.",
            "View Listings": "Ver listados",
            "Payments": "Pagos",
            "Cards": "Tarjetas",
            "UPI": "UPI",
            "Add credit or debit cards": "Agregar tarjetas de crédito o débito",
            "Google Pay UPI": "Google Pay UPI",
            "PhonePe UPI": "PhonePe UPI",
            "BHIM UPI": "BHIM UPI",
            "Add new UPI ID": "Agregar nuevo ID UPI",
            "Add": "Agregar",
            "Dashboard": "Panel",
            "Breakdown": "Desglose",
            "Failed to load dashboard data": "Error al cargar datos del panel",
            "Retry": "Reintentar",
            "Recent Searches": "Búsquedas recientes",
            "Terms and Conditions": "Términos y condiciones",
            "Book Now": "Reservar ahora",
            "No %@ listings": "Sin listados %@",
            "%d listings • %d available • %d sold": "%d listados • %d disponibles • %d vendidos",
            "Are you sure you want to delete \"%@\"?": "¿Estás seguro de que quieres eliminar \"%@\"?",
            "%d views": "%d vistas",
            "Qty: %d": "Cant: %d",
            "Buyer: %@": "Comprador: %@",
            "Order #%@": "Pedido #%@",
            "Placed on %@": "Realizado el %@",
            "Total: ₹%@": "Total: ₹%@",
            "Total: ₹%d": "Total: ₹%d",
            "+%d more items →": "+%d más artículos →",
            "+%d more item →": "+%d más artículo →",
            "No items": "Sin artículos",
            "Don't worry! Enter your email address and we'll send\nyou a link to reset your password.": "¡No te preocupes! Ingresa tu correo electrónico y te enviaremos un enlace para restablecer tu contraseña.",
            "We've sent a password reset link to %@. Please check your inbox and spam folder.": "Hemos enviado un enlace de restablecimiento a %@. Revisa tu bandeja de entrada y carpeta de spam.",
        ],

        // MARK: French
        .french: [
            "Home": "Accueil",
            "Search": "Rechercher",
            "Sell": "Vendre",
            "Post": "Publier",
            "Chat": "Discussion",
            "Account": "Compte",

            "Settings": "Paramètres",
            "Preferences": "Préférences",
            "Support": "Support",
            "Security": "Sécurité",
            "Account Actions": "Actions du Compte",
            "Language": "Langue",
            "Push Notifications": "Notifications Push",
            "Email Marketing": "Marketing par Email",
            "Contact Us": "Contactez-nous",
            "Rate Our App": "Notez Notre App",
            "Change Password": "Changer le Mot de Passe",
            "Biometric Login": "Connexion Biométrique",
            "Sign Out": "Déconnexion",
            "Delete Account": "Supprimer le Compte",

            "Choose the language": "Choisissez la langue",
            "Select your preferred language below. This helps us serve you better.": "Sélectionnez votre langue préférée ci-dessous. Cela nous aide à mieux vous servir.",
            "You Selected": "Vous avez sélectionné",
            "All Languages": "Toutes les Langues",

            "Enter old password:": "Entrez l'ancien mot de passe :",
            "Enter new password:": "Entrez le nouveau mot de passe :",
            "Old Password": "Ancien Mot de Passe",
            "New Password": "Nouveau Mot de Passe",
            "Forgot Password?": "Mot de Passe Oublié ?",
            "Save": "Enregistrer",
            "Password Changed": "Mot de Passe Changé",
            "Your password has been updated successfully.": "Votre mot de passe a été mis à jour avec succès.",

            "Set New Password": "Définir un Nouveau Mot de Passe",
            "Enter and confirm your new password below.": "Entrez et confirmez votre nouveau mot de passe ci-dessous.",
            "Reset Your Password": "Réinitialiser Votre Mot de Passe",
            "Confirm Password": "Confirmer le Mot de Passe",
            "College Email": "Email Universitaire",
            "Update Password": "Mettre à Jour le Mot de Passe",
            "Send Reset Link": "Envoyer le Lien de Réinitialisation",
            "Back to Login.": "Retour à la Connexion.",
            "Password Updated": "Mot de Passe Mis à Jour",
            "Your password has been changed successfully.": "Votre mot de passe a été changé avec succès.",
            "Reset Link Sent": "Lien de Réinitialisation Envoyé",

            "How Can We Reach You?": "Comment pouvons-nous vous joindre ?",
            "What Can We Help You With?": "Comment pouvons-nous vous aider ?",
            "Briefly Explain What's Going On": "Expliquez brièvement ce qui se passe",
            "Email": "Email",
            "Phone": "Téléphone",
            "Email Address": "Adresse Email",
            "Phone Number": "Numéro de Téléphone",
            "Subject": "Sujet",
            "Message": "Message",
            "Submit": "Soumettre",
            "Help": "Aide",
            "Bug Report": "Rapport de Bug",
            "Feedback": "Commentaires",
            "Account Issue": "Problème de Compte",
            "Write your message here...": "Écrivez votre message ici...",

            "OK": "OK",
            "Cancel": "Annuler",
            "Continue": "Continuer",
            "Get Help": "Obtenir de l'Aide",
            "Back": "Retour",
            "Loading...": "Chargement...",
            "Error": "Erreur",
            "Success": "Succès",
            "Delete": "Supprimer",
            "Done": "Terminé",
            "Edit": "Modifier",
            "Discard": "Annuler",
            "All": "Tous",

            "Trending Categories": "Catégories Tendance",
            "Categories": "Catégories",
            "See All": "Voir Tout",
            "Popular Items": "Articles Populaires",
            "Most Popular": "Plus Populaire",
            "Negotiable": "Négociable",
            "Hostel Essentials": "Essentiels du Foyer",
            "Furniture": "Meubles",
            "Fashion": "Mode",
            "Sports": "Sports",
            "Gadgets": "Gadgets",

            "No conversations yet": "Pas encore de conversations",
            "Start chatting with sellers\nby tapping Chat on a product": "Commencez à discuter avec les vendeurs\nen appuyant sur Discussion sur un produit",
            "Type a message...": "Tapez un message...",
            "Start a conversation": "Démarrer une conversation",
            "Selling": "Vente",
            "Buying": "Achat",
            "Buyer": "Acheteur",
            "Seller": "Vendeur",
            "Sending photo...": "Envoi de la photo...",
            "Failed to Send": "Échec de l'Envoi",
            "Could not send the photo. Please try again.": "Impossible d'envoyer la photo. Veuillez réessayer.",

            "My Orders": "Mes Commandes",
            "Order Details": "Détails de la Commande",
            "Pending": "En Attente",
            "Confirmed": "Confirmé",
            "Delivered": "Livré",
            "Cancelled": "Annulé",
            "Processing": "En Cours",
            "No orders yet": "Pas encore de commandes",
            "Failed to load orders": "Échec du chargement des commandes",
            "Order Timeline": "Chronologie de la Commande",
            "Order Items": "Articles de la Commande",
            "Delivery Information": "Informations de Livraison",
            "Order Summary": "Résumé de la Commande",
            "Subtotal": "Sous-total",
            "Negotiation Discount": "Remise de Négociation",
            "Total": "Total",
            "Rate Order": "Noter la Commande",
            "Order Confirmed": "Commande Confirmée",
            "Order Placed": "Commande Passée",
            "Order Delivered": "Commande Livrée",
            "Order Declined": "Commande Refusée",
            "Ready for Handoff": "Prêt pour la Remise",
            "Ready to Meet": "Prêt à Se Rencontrer",
            "Verify Code": "Vérifier le Code",
            "Enter 6-digit code": "Entrez le code à 6 chiffres",
            "Loading order items...": "Chargement des articles...",
            "Colour": "Couleur",
            "Size": "Taille",
            "Quantity": "Quantité",
            "Confirm Order": "Confirmer la Commande",
            "Place Order": "Passer la Commande",
            "Accept Order": "Accepter la Commande",
            "Reject Order": "Refuser la Commande",

            "My Listings": "Mes Annonces",
            "No listings yet": "Pas encore d'annonces",
            "Search listings...": "Rechercher des annonces...",
            "Available": "Disponible",
            "Sold": "Vendu",
            "Start selling by posting\nyour first item": "Commencez à vendre en publiant\nvotre premier article",
            "No results found": "Aucun résultat trouvé",
            "Try a different search term": "Essayez un autre terme de recherche",
            "Items with this status\nwill appear here": "Les articles avec ce statut\napparaîtront ici",
            "Cannot Edit": "Impossible de Modifier",
            "Once sold, listing cannot be edited.": "Une fois vendue, l'annonce ne peut pas être modifiée.",
            "Delete Listing": "Supprimer l'Annonce",
            "Edit Listing": "Modifier l'Annonce",

            "Description": "Description",
            "Features": "Caractéristiques",
            "Condition": "État",
            "Deal": "Offre",
            "Item Unavailable": "Article Indisponible",
            "No description available.": "Aucune description disponible.",
            "No features listed.": "Aucune caractéristique listée.",

            "Post Item": "Publier un Article",
            "Upload Photos": "Télécharger des Photos",
            "Product Details": "Détails du Produit",
            "Product Name": "Nom du Produit",
            "Price (in Rupees)": "Prix (en Roupies)",
            "Category": "Catégorie",
            "Upload Product": "Télécharger le Produit",
            "Non-Negotiable": "Non Négociable",
            "Authentication Required": "Authentification Requise",
            "Please log in to post items": "Connectez-vous pour publier des articles",
            "Missing Information": "Informations Manquantes",
            "Please fill in all required fields": "Veuillez remplir tous les champs requis",
            "Product uploaded successfully!": "Produit téléchargé avec succès !",
            "Save Changes": "Enregistrer les Modifications",
            "Update Listing": "Mettre à Jour l'Annonce",

            "Notifications": "Notifications",
            "No notifications yet": "Pas encore de notifications",
            "Failed to load notifications": "Échec du chargement des notifications",

            "Profile": "Profil",
            "Personal Information": "Informations Personnelles",
            "Hotspot Information": "Informations du Point de Rencontre",
            "First Name": "Prénom",
            "Last Name": "Nom",
            "Date of Birth": "Date de Naissance",
            "Gender": "Genre",
            "Address": "Adresse",
            "City": "Ville",
            "State": "État",
            "ZIP Code": "Code Postal",
            "Male": "Homme",
            "Female": "Femme",
            "Neutral": "Neutre",
            "Email Notifications": "Notifications par Email",
            "SMS Notifications": "Notifications SMS",
            "Edit Profile": "Modifier le Profil",
            "Discard Changes?": "Annuler les Modifications ?",
            "You have unsaved changes. Are you sure you want to go back?": "Vous avez des modifications non enregistrées. Voulez-vous vraiment revenir ?",

            "My Wishlist": "Ma Liste de Souhaits",
            "Wishlist": "Liste de Souhaits",
            "My Addresses": "Mes Adresses",
            "Terms & Conditions": "Conditions Générales",
            "Privacy Policy": "Politique de Confidentialité",

            "Add New Address": "Ajouter une Nouvelle Adresse",
            "Add Address": "Ajouter une Adresse",
            "Street": "Rue",
            "Country": "Pays",

            "Delivery Address": "Adresse de Livraison",
            "Change": "Modifier",
            "Payment Method": "Méthode de Paiement",
            "Cash on Delivery": "Paiement à la Livraison",
            "Special Instructions": "Instructions Spéciales",
            "Review": "Vérifier",
            "Payment": "Paiement",

            "Events": "Événements",
            "Browse Events": "Parcourir les Événements",

            // Post Chooser & Post Event
            "What would you like to post?": "Que souhaitez-vous publier ?",
            "Choose an option below to get started.": "Choisissez une option ci-dessous pour commencer.",
            "Post an Item": "Publier un Article",
            "Post an Event": "Publier un Événement",
            "List a product for sale on the marketplace.": "Publiez un produit à vendre sur le marché.",
            "Create a campus event for others to discover.": "Créez un événement universitaire que d'autres pourront découvrir.",
            "Post Event": "Publier l'Événement",
            "Event Details": "Détails de l'Événement",
            "Event Title": "Titre de l'Événement",
            "Venue": "Lieu",
            "Date": "Date",
            "Time": "Heure",
            "Free Event": "Événement Gratuit",
            "Tap to add an event image": "Appuyez pour ajouter une image de l'événement",
            "Describe your event...": "Décrivez votre événement...",
            "Your event has been posted successfully!": "Votre événement a été publié avec succès !",
            "Your Event has been posted!": "Votre Événement a été publié !",
            "Users can now discover and register for your event.": "Les utilisateurs peuvent maintenant découvrir et s'inscrire à votre événement.",
            "View Events": "Voir les Événements",
            "Please enter a valid price or mark the event as free.": "Veuillez entrer un prix valide ou marquer l'événement comme gratuit.",
            "Please fill in all required fields.": "Veuillez remplir tous les champs obligatoires.",

            "Login": "Connexion",
            "Welcome Back": "Bon Retour",
            "Sign Up": "Inscription",
            "Create Account": "Créer un Compte",
            "Password": "Mot de Passe",
            "Already have an account?": "Vous avez déjà un compte ?",
            "Account Created": "Compte Créé",
            "Get Started": "Commencer",
            "Welcome": "Bienvenue",
            "Order Placed!": "Commande Passée !",
            "Continue Shopping": "Continuer les Achats",
            "View Order": "Voir la Commande",

            "Rate Unizo": "Notez Unizo",
            "You'll be redirected to our app page on the App Store where you can leave a rating and review.": "Vous serez redirigé vers notre page sur l'App Store où vous pourrez laisser une note et un avis.",

            "Are you sure you want to sign out?": "Êtes-vous sûr de vouloir vous déconnecter ?",
            "Are you sure you want to delete your account? This action cannot be undone.": "Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est irréversible.",

            "Show this code to the seller when you meet to confirm delivery.": "Montrez ce code au vendeur lors de votre rencontre pour confirmer la livraison.",
            "Enter the code the buyer shows you to confirm delivery.": "Entrez le code que l'acheteur vous montre pour confirmer la livraison.",
            "Please enter the full 6-digit code.": "Veuillez entrer le code complet à 6 chiffres.",
            "Incorrect code. Please try again.": "Code incorrect. Veuillez réessayer.",
            "Something went wrong. Please try again.": "Quelque chose s'est mal passé. Veuillez réessayer.",

            // New Localization Keys
            "Failed to sign out: %@": "Échec de la déconnexion : %@",
            "Are you sure you want to delete your account? This action cannot be undone and all your data will be permanently removed.": "Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est irréversible et toutes vos données seront définitivement supprimées.",
            "Failed to delete account: %@": "Échec de la suppression du compte : %@",
            "Guest": "Invité",
            "Not signed in": "Non connecté",
            "Edit Hotspot": "Modifier le point de rencontre",
            "Set as default hotspot": "Définir comme point par défaut",
            "Your Product has been posted!": "Votre produit a été publié !",
            "We'll reach out to the best valued customers.": "Nous contacterons les meilleurs clients.",
            "View Listings": "Voir les annonces",
            "Payments": "Paiements",
            "Cards": "Cartes",
            "UPI": "UPI",
            "Add credit or debit cards": "Ajouter des cartes de crédit ou débit",
            "Google Pay UPI": "Google Pay UPI",
            "PhonePe UPI": "PhonePe UPI",
            "BHIM UPI": "BHIM UPI",
            "Add new UPI ID": "Ajouter un nouvel ID UPI",
            "Add": "Ajouter",
            "Dashboard": "Tableau de bord",
            "Breakdown": "Détails",
            "Failed to load dashboard data": "Échec du chargement des données",
            "Retry": "Réessayer",
            "Recent Searches": "Recherches récentes",
            "Terms and Conditions": "Termes et conditions",
            "Book Now": "Réserver maintenant",
            "No %@ listings": "Aucune annonce %@",
            "%d listings • %d available • %d sold": "%d annonces • %d disponibles • %d vendues",
            "Are you sure you want to delete \"%@\"?": "Êtes-vous sûr de vouloir supprimer \"%@\" ?",
            "%d views": "%d vues",
            "Qty: %d": "Qté : %d",
            "Buyer: %@": "Acheteur : %@",
            "Order #%@": "Commande #%@",
            "Placed on %@": "Passée le %@",
            "Total: ₹%@": "Total : ₹%@",
            "Total: ₹%d": "Total : ₹%d",
            "+%d more items →": "+%d articles de plus →",
            "+%d more item →": "+%d article de plus →",
            "No items": "Aucun article",
            "Don't worry! Enter your email address and we'll send\nyou a link to reset your password.": "Ne vous inquiétez pas ! Entrez votre adresse e-mail et nous vous enverrons un lien pour réinitialiser votre mot de passe.",
            "We've sent a password reset link to %@. Please check your inbox and spam folder.": "Nous avons envoyé un lien de réinitialisation à %@. Veuillez vérifier votre boîte de réception et votre dossier spam.",
        ],

        // MARK: German
        .german: [
            "Home": "Startseite",
            "Search": "Suchen",
            "Sell": "Verkaufen",
            "Post": "Erstellen",
            "Chat": "Chat",
            "Account": "Konto",

            "Settings": "Einstellungen",
            "Preferences": "Einstellungen",
            "Support": "Support",
            "Security": "Sicherheit",
            "Account Actions": "Kontoaktionen",
            "Language": "Sprache",
            "Push Notifications": "Push-Benachrichtigungen",
            "Email Marketing": "E-Mail-Marketing",
            "Contact Us": "Kontaktiere uns",
            "Rate Our App": "Bewerte unsere App",
            "Change Password": "Passwort ändern",
            "Biometric Login": "Biometrische Anmeldung",
            "Sign Out": "Abmelden",
            "Delete Account": "Konto löschen",

            "Choose the language": "Sprache wählen",
            "Select your preferred language below. This helps us serve you better.": "Wählen Sie unten Ihre bevorzugte Sprache. Dies hilft uns, Sie besser zu bedienen.",
            "You Selected": "Sie haben gewählt",
            "All Languages": "Alle Sprachen",

            "Enter old password:": "Altes Passwort eingeben:",
            "Enter new password:": "Neues Passwort eingeben:",
            "Old Password": "Altes Passwort",
            "New Password": "Neues Passwort",
            "Forgot Password?": "Passwort vergessen?",
            "Save": "Speichern",
            "Password Changed": "Passwort Geändert",
            "Your password has been updated successfully.": "Ihr Passwort wurde erfolgreich aktualisiert.",

            "Set New Password": "Neues Passwort Festlegen",
            "Enter and confirm your new password below.": "Geben Sie unten Ihr neues Passwort ein und bestätigen Sie es.",
            "Reset Your Password": "Passwort Zurücksetzen",
            "Confirm Password": "Passwort Bestätigen",
            "College Email": "Hochschul-E-Mail",
            "Update Password": "Passwort Aktualisieren",
            "Send Reset Link": "Rücksetzlink Senden",
            "Back to Login.": "Zurück zur Anmeldung.",
            "Password Updated": "Passwort Aktualisiert",
            "Your password has been changed successfully.": "Ihr Passwort wurde erfolgreich geändert.",
            "Reset Link Sent": "Rücksetzlink Gesendet",

            "How Can We Reach You?": "Wie können wir Sie erreichen?",
            "What Can We Help You With?": "Wie können wir Ihnen helfen?",
            "Briefly Explain What's Going On": "Erklären Sie kurz, was los ist",
            "Email": "E-Mail",
            "Phone": "Telefon",
            "Email Address": "E-Mail-Adresse",
            "Phone Number": "Telefonnummer",
            "Subject": "Betreff",
            "Message": "Nachricht",
            "Submit": "Absenden",
            "Help": "Hilfe",
            "Bug Report": "Fehlerbericht",
            "Feedback": "Feedback",
            "Account Issue": "Kontoproblem",
            "Write your message here...": "Schreiben Sie hier Ihre Nachricht...",

            "OK": "OK",
            "Cancel": "Abbrechen",
            "Continue": "Weiter",
            "Get Help": "Hilfe erhalten",
            "Back": "Zurück",
            "Loading...": "Laden...",
            "Error": "Fehler",
            "Success": "Erfolg",
            "Delete": "Löschen",
            "Done": "Fertig",
            "Edit": "Bearbeiten",
            "Discard": "Verwerfen",
            "All": "Alle",

            "Trending Categories": "Trendkategorien",
            "Categories": "Kategorien",
            "See All": "Alle anzeigen",
            "Popular Items": "Beliebte Artikel",
            "Most Popular": "Am Beliebtesten",
            "Negotiable": "Verhandelbar",
            "Hostel Essentials": "Wohnheim-Essentials",
            "Furniture": "Möbel",
            "Fashion": "Mode",
            "Sports": "Sport",
            "Gadgets": "Gadgets",

            "No conversations yet": "Noch keine Unterhaltungen",
            "Start chatting with sellers\nby tapping Chat on a product": "Beginnen Sie mit Verkäufern zu chatten\nindem Sie auf Chat bei einem Produkt tippen",
            "Type a message...": "Nachricht eingeben...",
            "Start a conversation": "Unterhaltung beginnen",
            "Selling": "Verkauf",
            "Buying": "Kauf",
            "Buyer": "Käufer",
            "Seller": "Verkäufer",
            "Sending photo...": "Foto wird gesendet...",
            "Failed to Send": "Senden fehlgeschlagen",
            "Could not send the photo. Please try again.": "Foto konnte nicht gesendet werden. Bitte versuchen Sie es erneut.",

            "My Orders": "Meine Bestellungen",
            "Order Details": "Bestelldetails",
            "Pending": "Ausstehend",
            "Confirmed": "Bestätigt",
            "Delivered": "Geliefert",
            "Cancelled": "Storniert",
            "Processing": "In Bearbeitung",
            "No orders yet": "Noch keine Bestellungen",
            "Failed to load orders": "Bestellungen konnten nicht geladen werden",
            "Order Timeline": "Bestellverlauf",
            "Order Items": "Bestellartikel",
            "Delivery Information": "Lieferinformationen",
            "Order Summary": "Bestellübersicht",
            "Subtotal": "Zwischensumme",
            "Negotiation Discount": "Verhandlungsrabatt",
            "Total": "Gesamt",
            "Rate Order": "Bestellung Bewerten",
            "Order Confirmed": "Bestellung Bestätigt",
            "Order Placed": "Bestellung Aufgegeben",
            "Order Delivered": "Bestellung Geliefert",
            "Order Declined": "Bestellung Abgelehnt",
            "Ready for Handoff": "Bereit zur Übergabe",
            "Ready to Meet": "Bereit zum Treffen",
            "Verify Code": "Code Überprüfen",
            "Enter 6-digit code": "6-stelligen Code eingeben",
            "Loading order items...": "Bestellartikel werden geladen...",
            "Colour": "Farbe",
            "Size": "Größe",
            "Quantity": "Menge",
            "Confirm Order": "Bestellung Bestätigen",
            "Place Order": "Bestellung Aufgeben",
            "Accept Order": "Bestellung Annehmen",
            "Reject Order": "Bestellung Ablehnen",

            "My Listings": "Meine Angebote",
            "No listings yet": "Noch keine Angebote",
            "Search listings...": "Angebote suchen...",
            "Available": "Verfügbar",
            "Sold": "Verkauft",
            "Start selling by posting\nyour first item": "Starten Sie den Verkauf\nmit Ihrem ersten Artikel",
            "No results found": "Keine Ergebnisse gefunden",
            "Try a different search term": "Versuchen Sie einen anderen Suchbegriff",
            "Items with this status\nwill appear here": "Artikel mit diesem Status\nerscheinen hier",
            "Cannot Edit": "Bearbeitung nicht möglich",
            "Once sold, listing cannot be edited.": "Einmal verkauft, kann das Angebot nicht bearbeitet werden.",
            "Delete Listing": "Angebot Löschen",
            "Edit Listing": "Angebot Bearbeiten",

            "Description": "Beschreibung",
            "Features": "Merkmale",
            "Condition": "Zustand",
            "Deal": "Angebot",
            "Item Unavailable": "Artikel Nicht Verfügbar",
            "No description available.": "Keine Beschreibung verfügbar.",
            "No features listed.": "Keine Merkmale aufgelistet.",

            "Post Item": "Artikel Einstellen",
            "Upload Photos": "Fotos Hochladen",
            "Product Details": "Produktdetails",
            "Product Name": "Produktname",
            "Price (in Rupees)": "Preis (in Rupien)",
            "Category": "Kategorie",
            "Upload Product": "Produkt Hochladen",
            "Non-Negotiable": "Nicht Verhandelbar",
            "Authentication Required": "Authentifizierung Erforderlich",
            "Please log in to post items": "Bitte melden Sie sich an, um Artikel einzustellen",
            "Missing Information": "Fehlende Informationen",
            "Please fill in all required fields": "Bitte füllen Sie alle Pflichtfelder aus",
            "Product uploaded successfully!": "Produkt erfolgreich hochgeladen!",
            "Save Changes": "Änderungen Speichern",
            "Update Listing": "Angebot Aktualisieren",

            "Notifications": "Benachrichtigungen",
            "No notifications yet": "Noch keine Benachrichtigungen",
            "Failed to load notifications": "Benachrichtigungen konnten nicht geladen werden",

            "Profile": "Profil",
            "Personal Information": "Persönliche Informationen",
            "Hotspot Information": "Treffpunkt-Informationen",
            "First Name": "Vorname",
            "Last Name": "Nachname",
            "Date of Birth": "Geburtsdatum",
            "Gender": "Geschlecht",
            "Address": "Adresse",
            "City": "Stadt",
            "State": "Bundesland",
            "ZIP Code": "Postleitzahl",
            "Male": "Männlich",
            "Female": "Weiblich",
            "Neutral": "Neutral",
            "Email Notifications": "E-Mail-Benachrichtigungen",
            "SMS Notifications": "SMS-Benachrichtigungen",
            "Edit Profile": "Profil bearbeiten",
            "Discard Changes?": "Änderungen verwerfen?",
            "You have unsaved changes. Are you sure you want to go back?": "Sie haben ungespeicherte Änderungen. Möchten Sie wirklich zurückgehen?",

            "My Wishlist": "Meine Wunschliste",
            "Wishlist": "Wunschliste",
            "My Addresses": "Meine Adressen",
            "Terms & Conditions": "Allgemeine Geschäftsbedingungen",
            "Privacy Policy": "Datenschutzrichtlinie",

            "Add New Address": "Neue Adresse Hinzufügen",
            "Add Address": "Adresse Hinzufügen",
            "Street": "Straße",
            "Country": "Land",

            "Delivery Address": "Lieferadresse",
            "Change": "Ändern",
            "Payment Method": "Zahlungsmethode",
            "Cash on Delivery": "Nachnahme",
            "Special Instructions": "Besondere Anweisungen",
            "Review": "Überprüfen",
            "Payment": "Zahlung",

            "Events": "Veranstaltungen",
            "Browse Events": "Veranstaltungen Durchsuchen",

            // Post Chooser & Post Event
            "What would you like to post?": "Was möchten Sie veröffentlichen?",
            "Choose an option below to get started.": "Wählen Sie eine Option unten, um loszulegen.",
            "Post an Item": "Artikel Veröffentlichen",
            "Post an Event": "Veranstaltung Erstellen",
            "List a product for sale on the marketplace.": "Veröffentlichen Sie ein Produkt zum Verkauf auf dem Marktplatz.",
            "Create a campus event for others to discover.": "Erstellen Sie eine Campus-Veranstaltung, die andere entdecken können.",
            "Post Event": "Veranstaltung Erstellen",
            "Event Details": "Veranstaltungsdetails",
            "Event Title": "Veranstaltungstitel",
            "Venue": "Veranstaltungsort",
            "Date": "Datum",
            "Time": "Uhrzeit",
            "Free Event": "Kostenlose Veranstaltung",
            "Tap to add an event image": "Tippen Sie, um ein Veranstaltungsbild hinzuzufügen",
            "Describe your event...": "Beschreiben Sie Ihre Veranstaltung...",
            "Your event has been posted successfully!": "Ihre Veranstaltung wurde erfolgreich veröffentlicht!",
            "Your Event has been posted!": "Ihre Veranstaltung wurde veröffentlicht!",
            "Users can now discover and register for your event.": "Benutzer können Ihre Veranstaltung jetzt entdecken und sich registrieren.",
            "View Events": "Veranstaltungen Anzeigen",
            "Please enter a valid price or mark the event as free.": "Geben Sie einen gültigen Preis ein oder markieren Sie die Veranstaltung als kostenlos.",
            "Please fill in all required fields.": "Bitte füllen Sie alle Pflichtfelder aus.",

            "Login": "Anmelden",
            "Welcome Back": "Willkommen Zurück",
            "Sign Up": "Registrieren",
            "Create Account": "Konto Erstellen",
            "Password": "Passwort",
            "Already have an account?": "Haben Sie bereits ein Konto?",
            "Account Created": "Konto Erstellt",
            "Get Started": "Loslegen",
            "Welcome": "Willkommen",
            "Order Placed!": "Bestellung Aufgegeben!",
            "Continue Shopping": "Weiter Einkaufen",
            "View Order": "Bestellung Anzeigen",

            "Rate Unizo": "Bewerte Unizo",
            "You'll be redirected to our app page on the App Store where you can leave a rating and review.": "Sie werden zu unserer App-Seite im App Store weitergeleitet, wo Sie eine Bewertung abgeben können.",

            "Are you sure you want to sign out?": "Sind Sie sicher, dass Sie sich abmelden möchten?",
            "Are you sure you want to delete your account? This action cannot be undone.": "Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.",

            "Show this code to the seller when you meet to confirm delivery.": "Zeigen Sie dem Verkäufer diesen Code, wenn Sie sich treffen, um die Lieferung zu bestätigen.",
            "Enter the code the buyer shows you to confirm delivery.": "Geben Sie den Code ein, den der Käufer Ihnen zeigt, um die Lieferung zu bestätigen.",
            "Please enter the full 6-digit code.": "Bitte geben Sie den vollständigen 6-stelligen Code ein.",
            "Incorrect code. Please try again.": "Falscher Code. Bitte versuchen Sie es erneut.",
            "Something went wrong. Please try again.": "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",

            // New Localization Keys
            "Failed to sign out: %@": "Abmeldung fehlgeschlagen: %@",
            "Are you sure you want to delete your account? This action cannot be undone and all your data will be permanently removed.": "Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden und alle Ihre Daten werden dauerhaft entfernt.",
            "Failed to delete account: %@": "Konto konnte nicht gelöscht werden: %@",
            "Guest": "Gast",
            "Not signed in": "Nicht angemeldet",
            "Edit Hotspot": "Treffpunkt bearbeiten",
            "Set as default hotspot": "Als Standard-Treffpunkt festlegen",
            "Your Product has been posted!": "Ihr Produkt wurde veröffentlicht!",
            "We'll reach out to the best valued customers.": "Wir erreichen die besten Kunden.",
            "View Listings": "Angebote ansehen",
            "Payments": "Zahlungen",
            "Cards": "Karten",
            "UPI": "UPI",
            "Add credit or debit cards": "Kredit- oder Debitkarten hinzufügen",
            "Google Pay UPI": "Google Pay UPI",
            "PhonePe UPI": "PhonePe UPI",
            "BHIM UPI": "BHIM UPI",
            "Add new UPI ID": "Neue UPI-ID hinzufügen",
            "Add": "Hinzufügen",
            "Dashboard": "Dashboard",
            "Breakdown": "Aufschlüsselung",
            "Failed to load dashboard data": "Dashboard-Daten konnten nicht geladen werden",
            "Retry": "Erneut versuchen",
            "Recent Searches": "Letzte Suchen",
            "Terms and Conditions": "Geschäftsbedingungen",
            "Book Now": "Jetzt buchen",
            "No %@ listings": "Keine %@-Angebote",
            "%d listings • %d available • %d sold": "%d Angebote • %d verfügbar • %d verkauft",
            "Are you sure you want to delete \"%@\"?": "Sind Sie sicher, dass Sie \"%@\" löschen möchten?",
            "%d views": "%d Aufrufe",
            "Qty: %d": "Menge: %d",
            "Buyer: %@": "Käufer: %@",
            "Order #%@": "Bestellung #%@",
            "Placed on %@": "Bestellt am %@",
            "Total: ₹%@": "Gesamt: ₹%@",
            "Total: ₹%d": "Gesamt: ₹%d",
            "+%d more items →": "+%d weitere Artikel →",
            "+%d more item →": "+%d weiterer Artikel →",
            "No items": "Keine Artikel",
            "Don't worry! Enter your email address and we'll send\nyou a link to reset your password.": "Keine Sorge! Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts.",
            "We've sent a password reset link to %@. Please check your inbox and spam folder.": "Wir haben einen Link zum Zurücksetzen des Passworts an %@ gesendet. Bitte überprüfen Sie Ihren Posteingang und Spam-Ordner.",
        ]
    ]
}

// MARK: - String Extension
extension String {
    /// Returns the translated version of this string based on the current app language.
    var localized: String {
        AppLanguageManager.shared.localized(self)
    }
}

// MARK: - Notification for Language Change
extension Notification.Name {
    static let appLanguageDidChange = Notification.Name("appLanguageDidChange")
}
